In [ ]:
import numpy as np

arr = np.array([2,5,10,5])
print(type(arr))  # numpy.ndarray
print(arr)

arr2d = np.array([[2,3],[9,10],['Peter','Ken']]) # 2d array
print(arr2d)  # class still be numpy.ndarray

print(arr+1) # [3,6,11,6] every item +1  #mechanism : Loop
print(arr*2) #[4,10,20,10]

list2 = [2,5,10,5]
#print(list2+1)   #! error
print(list2*2)   #! list's operation is different

# print(arr2d+1) #error, coz String array cannot + 1

print(np.sum(arr)) #np method ->np array
print(np.sum([3,7,8]))

list1 = [3,7,8]
print(np.sum(list1)) # list still can use

#Method in math still exist in np  ,nice :)
print(np.min(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))
print(np.max(arr))
print(np.sort(arr))
print(np.unique(arr)) #remove dup

print(arr) #methods are immutable




<class 'numpy.ndarray'>
[ 2  5 10  5]
[['2' '3']
 ['9' '10']
 ['Peter' 'Ken']]
[ 3  6 11  6]
[ 4 10 20 10]
[10, 100, -2, 10, 100, -2]
22
18
18
2
5.5
5.0
2.8722813232690143
8.25
10
[ 2  5  5 10]
[ 2  5 10]
[ 2  5 10  5]
